In [2]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
import time

from glob import glob
from itertools import cycle

import librosa
import librosa.display
import IPython.display as ipd


In [3]:
sns.set_theme(style="white", palette = None)
color_pal = plt.rcParams["axes.prop_cycle"].by_key()["color"]
color_cycle = cycle(plt.rcParams["axes.prop_cycle"].by_key()["color"])

In [4]:
class0 = glob("./data/Class0/*/*.mp3")
class1 = glob("./data/Class1/*/*.mp3")

In [5]:
#normalize recordings to 0-1 scale
y, sr = librosa.load(class0[0])
y_norm = librosa.util.normalize(y)

In [17]:
#remove silence
y_trim, _ = librosa.effects.trim(y_norm, top_db=20)
intervals = librosa.effects.split(y_trim, top_db=20)
audio_list = np.concatenate([y_trim[list[0]:list[1]] for list in intervals])
print(audio_list)

[-2.1801819e-03 -2.3870976e-03 -2.1663078e-03 ... -8.5686697e-05
 -3.6922444e-05  2.4164854e-05]


In [19]:
clip_length = 3
clip_length_samples = clip_length*sr
max_len = sr*60
#crop into 1 minute recording
y_cropped = audio_list[:max_len]

#cut into 3s clips
y_clips = librosa.util.frame(y_cropped,
                             frame_length=clip_length_samples,
                             hop_length=clip_length_samples).T
print(len(y_clips))
# print(y_clips.shape)
ipd.Audio(y_clips[0], rate=sr)

17


In [1]:
#spectograms
mel_spectograms = []
for clip in y_clips:
    S = librosa.feature.melspectrogram(y = clip, sr = sr, n_mels = 128,)
    S_db_mel = librosa.amplitude_to_db(S, ref=np.max)
    mel_spectograms.append(S_db_mel)

    ipd.clear_output(wait=True)
    fig, ax = plt.subplots(figsize = (10,5))
    img = librosa.display.specshow(S_db_mel, x_axis='time', y_axis='log', ax=ax, cmap='inferno')
    fig.colorbar(img, ax=ax, format = f'%0.2f')
    ipd.display(fig)
    S_pcen = librosa.pcen(S_db_mel, sr=sr)



NameError: name 'y_clips' is not defined

In [78]:
#input
X = np.array(mel_spectograms)
np.shape(X) #20 clips, 128 mels, #time steps??? <- co to

#labels
Y = np.ones(X.shape[0]) #create an array of 1's for each clip
# for x, y in zip(Y, X):
#     print(f"{y}: {x}")

[[-74.97419  -64.14318  -38.11953  ... -40.10911  -52.456608 -42.60328 ]
 [-51.193913 -44.255753 -23.618116 ... -21.529423 -33.736    -28.335697]
 [-34.204617 -20.906069 -23.390501 ... -23.864532 -34.08776  -30.401731]
 ...
 [-80.       -80.       -80.       ... -80.       -80.       -80.      ]
 [-80.       -80.       -80.       ... -80.       -80.       -80.      ]
 [-80.       -80.       -80.       ... -80.       -80.       -80.      ]]: 1.0
[[-32.330513 -27.906166 -30.805573 ... -48.17714  -48.243732 -48.941956]
 [-21.511368 -17.735508 -12.656879 ... -40.748478 -34.545853 -40.15228 ]
 [-23.73315  -16.82082  -16.675255 ... -34.64292  -28.336359 -27.13047 ]
 ...
 [-80.       -80.       -80.       ... -80.       -80.       -80.      ]
 [-80.       -80.       -80.       ... -80.       -80.       -80.      ]
 [-80.       -80.       -80.       ... -80.       -80.       -80.      ]]: 1.0
[[-54.554184 -50.758526 -41.160606 ... -56.897697 -57.32343  -65.65029 ]
 [-48.15507  -32.743416 -30.5